AWSTemplateFormatVersion: 2010-09-09
Description: Creates S3 bucket that triggers lambda to process text on addition
Resources:
  TextBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: text-submissions
